library(igraph)
#(a)
g <- sample_pa_age(1000, pa.exp=1, aging.exp=-1, aging.bin=1000, directed = FALSE)
pdf("p3_1.pdf")
plot(degree_distribution(g), main = "Degree Distribution", xlab="degree", ylab="density")
dev.off()

#(b)
structure <- cluster_fast_greedy(g)
print(paste("length: ", length(structure)))
print(paste("modularity: ", modularity(structure)))
pdf("p3_2_.pdf")
plot(structure, g, layout=layout.fruchterman.reingold(g, niter=10000), col = membership(structure),mark.groups = communities(structure), edge.color = c("black", "red")[crossing(structure,g) + 1],vertex.label=NA, vertex.size=5)
dev.off()
