library(igraph)
#(a)
Diameter = numeric(0)
for (i in 1:100){
  g <- sample_forestfire(1000, fw.prob=0.35, bw.factor=0.3/0.35)
  Diameter = c (Diameter, diameter(g))
}
dd1 <- degree_distribution(g, mode="in")
dd2 <- degree_distribution(g, mode="out")
pdf("p4_1.pdf")
plot(seq(along=dd1)-1, dd1, main = "In Degree Distribution", xlab="in degree", ylab="density")
dev.off()
pdf("p4_2.pdf")
plot(seq(along=dd2)-1, dd2, main = "Out Degree Distribution", xlab="out degree", ylab="density")
dev.off()

#(b)
print(paste("average diameter: ", mean(Diameter)))
# g <- sample_forestfire(1000, fw.prob=0.1, bw.factor=0.3/0.1)
# print(paste("diameter: ", diameter(g)))
# g <- sample_forestfire(1000, fw.prob=0.7, bw.factor=0.3/0.7)
# print(paste("diameter: ", diameter(g)))

#(c)
structure <- walktrap.community(g)
print(paste("length: ", length(structure)))
print(paste("modularity: ", modularity(structure)))
pdf("p4_3_.pdf")
#plot(structure, g, col = membership(structure),mark.groups = communities(structure), edge.color = c("black", "red")[crossing(structure,g) + 1],vertex.label=NA)
plot(structure, g, layout=layout.fruchterman.reingold(g, niter=10000), col = membership(structure),mark.groups = communities(structure), edge.color = c("black", "red")[crossing(structure,g) + 1],vertex.label=NA, vertex.size=5)
dev.off()

strucure <- edge.betweenness.community(g, directed=TRUE)
print(paste("length: ", length(structure)))
print(paste("modularity: ", modularity(structure)))
pdf("p4_4_.pdf")
#plot(structure, g, col = membership(structure),mark.groups = communities(structure), edge.color = c("black", "red")[crossing(structure,g) + 1],vertex.label=NA)
plot(structure, g, layout=layout.fruchterman.reingold(g, niter=10000), col = membership(structure),mark.groups = communities(structure), edge.color = c("black", "red")[crossing(structure,g) + 1],vertex.label=NA, vertex.size=5)
dev.off()